{{- if .Values.analysis.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ include "argo-rollouts-skill.fullname" . }}
  labels:
    {{- include "argo-rollouts-skill.labels" . | nindent 4 }}
spec:
  metrics:
    - name: success-rate
      interval: {{ .Values.analysis.interval }}
      successCondition: {{ .Values.analysis.successCondition | quote }}
      failureLimit: {{ .Values.analysis.failureLimit }}
      provider:
        {{- toYaml .Values.analysis.provider | nindent 8 }}
{{- end }}
